language: csharp
mono: none
dotnet: 2.0.0
os: linux
dist: trusty
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore ./IniWrapper/
  - dotnet build ./IniWrapper/
  - dotnet test ./IniWrapper/IniWrapper.IntegrationTests/IniWrapper.IntegrationTests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[NUnit*]*
  - dotnet test ./IniWrapper/IniWrapper.Tests/IniWrapper.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[NUnit*]*
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f ./IniWrapper/IniWrapper.IntegrationTests/coverage.xml